apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/minikube-addons: registry
spec:
  selector:
    actual-registry: "true"
    kubernetes.io/minikube-addons: registry
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30500  # The port exposed on the service
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30501  # If you want to enable https, you can change it to another port like 3501
  type: NodePort

